apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dalaba-fouta/projet-site.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true